language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
  - jruby-9.2
  - rbx-2
  - rbx-3
matrix:
  include:
    - rvm: 2.2
      before_install:
        - gem install bundler -v '< 2'
    - rvm: 2.6
      env: RUBYOPT=--jit LONG_RUN=true
    - rvm: ruby-head
      env: RUBYOPT=--jit LONG_RUN=true
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
    - rvm: rbx-3
bundler_args: --without local_development
